// ✅ 多語言模組（整合版）

function i18n(key) {
  const lang = localStorage.getItem("lang") || "zh-Hant";
  return (translations?.[lang]?.[key]) || key;
}

function applyLang(lang = localStorage.getItem("lang") || "zh-Hant") {
  const dict = translations[lang] || translations["zh-Hant"];

  // 所有內文元素
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) el.textContent = dict[key];
  });

  // select 選單內的 option
  document.querySelectorAll("option[data-i18n-option]").forEach(opt => {
    const key = opt.getAttribute("data-i18n-option");
    if (dict[key]) opt.textContent = dict[key];
  });

  // input 的 placeholder
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (dict[key]) el.placeholder = dict[key];
  });
}

const translations = {
 "zh-Hant": {
  title: "FINORA 好好存",
  subtitle: "讓資產更有力，退休不焦慮。",
  asset: "資產管理",
  compound: "複利試算",
  withdraw: "退休提領",
  emergency: "預備金試算",
  accountLabel: "帳本選擇：",
  rename: "✏️ 重新命名",
  add: "➕ 新增帳本",
  delete: "🗑️ 刪除帳本",
  save: "儲存",
  login: "🔐 使用 Google 帳號登入",
  logout: "🚪 登出",
  langLabel: "🌐 語言：",
  privacy: "FINORA 重視隱私。你的資產，只屬於你自己。",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA 好好存｜家庭友善資產整合工具",
  guide: "使用說明",
  contact: "聯絡我們",
  policy: "隱私權條款",
  placeholderNewAccount: "輸入新帳本名稱",
  asset_title: "登記你的好好資產",
  guide_select_type: "📢 從下方選單挑選資產種類（股票、保單、加密貨幣等）",
  guide_stock_auto: "💾 台股與美股會自動查詢最新現價",
  guide_currency_auto: "🔗 輸入外幣資產時，系統會自動帶入最新匯率",
  save_btn: "💾 儲存資產",
  asset_list: "資產列表",
  asset_total: "資產加總",
  back_to_home: "← 返回首頁",
  privacy_note: "🔐 所有資料皆保存在你的 Google 帳號與雲端帳本中，不用擔心遺失或外洩。",
  user: "使用者：",
  account: "帳本：",
  label_type: "種類：",
  label_name: "名稱：",
  label_amount: "金額：",
  label_currency: "幣別：",
  label_bank: "銀行名稱：",
  label_note: "備註：",
  label_display_currency: "💱 總資產顯示幣別：",
  option_please_select: "請選擇",
  option_stock: "股票",
  option_deposit: "定存",
  option_cash: "現金",
  option_property: "房產",
  option_insurance: "儲蓄保險",
  option_fund: "基金",
  option_crypto: "加密貨幣",
  option_other: "其他",
  option_股票: "股票",
  option_定存: "定存",
  option_現金: "現金",
  option_房產: "房產",
  option_儲蓄保險: "儲蓄保險",
  option_基金: "基金",
  option_加密貨幣: "加密貨幣",
  option_其他: "其他",
  footer_help: "使用說明",
  footer_contact: "聯絡我們",
  footer_privacy: "隱私權條款",
  not_logged_in: "（尚未登入）",
  no_account_selected: "（尚未選擇）",
  please_login_first: "⚠️ 尚未登入，請先登入 Google 帳號",
  init_error: "系統初始化錯誤，請重新整理頁面",
  total_asset: "總資產",
  exchange_rate_updated: "匯率更新時間",
  cost: "成本",
  current_price: "現價",
  market_value: "市值",
  profit: "盈餘",
  option_select: "請選擇",
  save_asset: "儲存資產",
howto_title: "使用說明",
howto_intro: "為自己、家庭與自由工作者打造的資產整合工具，清楚掌握財務現況，也陪孩子練習對錢有方向感。",
howto_feature1_title: "📒 分帳本管理更自由",
howto_feature1_text: "不同目標建立不同帳本，每個年齡層都適用。分開管理更清楚，人生目標井然有序。",
howto_feature2_title: "📈 複利成長模擬",
howto_feature2_text: "輸入初始金額、報酬率與定期投入金額，模擬資產在時間推動下的成長潛力，提早看到未來。",
howto_feature3_title: "💰 資產整合與幣別換算",
howto_feature3_text: "整合 ETF、基金、股票、保單、加密貨幣、現金與房產，自動計算總市值與盈餘，並支援台幣換算。",
howto_feature4_title: "⏳ 退休提領與風險試算",
howto_feature4_text: "依照目前資產與提領設定模擬退休現金流，幫你看見「可以支撐多久」的未來畫面，做出有感決策。",
howto_feature5_title: "🧯 緊急預備金試算工具",
howto_feature5_text: "輸入生活支出項目（如房租、食物、育兒），自動試算應準備的 3～6 個月緊急預備金金額，打造安全緩衝區。",
howto_feature6_title: "🔐 雲端同步 + Google 安全登入",
howto_feature6_text: "一鍵登入、自動儲存至雲端，支援多帳本、多裝置同步操作，資料僅屬於你，無干擾、無壓力。",
howto_cta: "立即開始使用",
howto_conclusion: "好好存，不只是記帳，而是你在為未來財務留下安全、自由與不慌張的底氣。",
privacy_title: "隱私權政策",
privacy_intro: "FINORA｜好好存，尊重並保護使用者的個人資料。以下是我們如何蒐集、使用及保護您的資訊。",
privacy_section1: "一、蒐集資訊",
privacy_content1: "我們僅會在使用者自願提供的情況下收集姓名、Email 等資訊。Google 登入僅用於個人資料同步，不會另作其他用途。",
privacy_section2: "二、資料用途",
privacy_content2: "收集的資料將僅用於帳本同步、功能使用分析與產品改善，不會出售或提供給第三方。",
privacy_section3: "三、資料儲存與安全",
privacy_content3: "所有資料均儲存在 Google Firebase Cloud，採用標準化加密與身份驗證保護。",
privacy_section4: "四、使用者權益",
privacy_content4: "使用者可隨時刪除帳本內容與個人資料。如欲刪除帳號，請來信聯絡我們。",
privacy_section5: "五、政策更新",
privacy_content5: "我們將視需求更新隱私政策。更新後將公佈於本頁，重大變更將另行通知使用者。",
privacy_start: "立即開始使用",
   compound_title: "複利試算｜FINORA",
    compound_intro: "🔢 輸入起始金額、年報酬率與時間,模擬複利增值的成長效果",
    currency_label: "資產總市值幣別：",
    total_asset_loading: "💰 資產加總讀取中...",
    total_asset_value: "💰 目前資產總市值（折合 {currency}）：",
    fetching_exchange: "📡 查詢最新匯率中...",
    invalid_exchange: "無效匯率資料",
    exchange_updated: "✅ 匯率更新完成",
    using_stored_exchange: "⚠️ 使用上次儲存的匯率資料",
    using_default_exchange: "⚠️ 使用預設匯率資料",
    exchange_not_ready: "⚠️ 匯率尚未就緒，無法顯示市值",
    no_assets: "⚠️ 尚未登記任何資產",
    compound_result_prefix: "投入 {years} 年後，期末總資產：約 ",
    unit_currency: "元",
    asset_category_summary: "📊 資產分類加總：",
    currency_totals: "💱 幣別總市值：",
    user: "使用者",
    account_book: "帳本",
    last_calculated: "🛎 最近一次試算結果：約",
    please_login: "請先登入後再使用此功能",
    no_account_warning: "⚠️ 找不到任何帳本，請先回首頁建立帳本",
    back_home_link: "← 返回首頁",
    footer_guide: "使用說明",
    footer_contact: "聯絡我們",
    footer_privacy: "隱私權條款",
    footer_copyright: "© 2025 FINORA 好好存｜家庭友善資產整合工具",
   label_principal: "初始投入金額（元）：",
label_rate: "年報酬率（%）：",
label_years: "投資年數：",
label_annual: "每年定期投入金額：",
label_monthly: "每月定期投入金額：",
compound_input_title: "📈 複利試算",
calculate_button: "計算複利",
last_calculated: "上次試算結果：",
   exchange_tool: "匯率換算",
label_amount: "金額：",
label_from: "從：",
label_to: "轉換為：",
convert_button: "換算",
exchange_updated: "✅ 匯率更新完成",
   type_股票: "股票",
type_基金: "基金",
type_加密貨幣: "加密貨幣",
type_儲蓄保險: "儲蓄保險",
type_現金: "現金",
type_房產: "房產",
type_定存: "定存",
type_其他: "其他",

},
  
 "zh-Hans": {
  title: "FINORA 好好存",
  subtitle: "让资产更有力，退休不焦虑。",
  asset: "资产管理",
  compound: "复利试算",
  withdraw: "退休提领",
  emergency: "预备金试算",
  accountLabel: "账本选择：",
  rename: "✏️ 重命名",
  add: "➕ 新增账本",
  delete: "🗑️ 删除账本",
  save: "保存",
  login: "🔐 使用 Google 账号登入",
  logout: "🚪 登出",
  langLabel: "🌐 语言：",
  privacy: "FINORA 重视隐私。你的资产，只属于你自己。",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA 好好存｜家庭友善资产整合工具",
  guide: "使用说明",
  contact: "联系我们",
  policy: "隐私条款",
  placeholderNewAccount: "输入新账本名称",
  asset_title: "登记你的好好资产",
  guide_select_type: "📢 从下方选单挑选资产种类（股票、保单、加密货币等）",
  guide_stock_auto: "💾 台股与美股会自动查询最新现价",
  guide_currency_auto: "🔗 输入外币资产时，系统会自动带入最新汇率",
  save_btn: "💾 保存资产",
  asset_list: "资产列表",
  asset_total: "资产总计",
  back_to_home: "← 返回首页",
  privacy_note: "🔐 所有资料皆保存在你的 Google 帐号与云端账本中，无需担心遗失或外泄。",
  user: "使用者：",
  account: "账本：",
  label_type: "种类：",
  label_name: "名称：",
  label_amount: "金额：",
  label_currency: "币别：",
  label_bank: "银行名称：",
  label_note: "备注：",
  label_display_currency: "💱 总资产显示币别：",
  option_please_select: "请选择",
  option_stock: "股票",
  option_deposit: "定存",
  option_cash: "现金",
  option_property: "房产",
  option_insurance: "储蓄保险",
  option_fund: "基金",
  option_crypto: "加密货币",
  option_other: "其他",
  option_股票: "股票",
  option_定存: "定存",
  option_現金: "现金",
  option_房產: "房产",
  option_儲蓄保險: "储蓄保险",
  option_基金: "基金",
  option_加密貨幣: "加密货币",
  option_其他: "其他",
  footer_help: "使用说明",
  footer_contact: "联系我们",
  footer_privacy: "隐私条款",
  not_logged_in: "（尚未登录）",
  no_account_selected: "（尚未选择）",
  please_login_first: "⚠️ 尚未登录，请先登录 Google 账号",
  init_error: "系统初始化错误，请重新刷新页面",
  total_asset: "总资产",
  exchange_rate_updated: "汇率更新时间",
  cost: "成本",
  current_price: "现价",
  market_value: "市值",
  profit: "盈余",
   option_select: "请选择",
save_asset: "保存资产",
   howto_title: "使用说明",
howto_intro: "为自己、家庭与自由工作者打造的资产整合工具，清楚掌握财务现况，也陪孩子练习对钱有方向感。",
howto_feature1_title: "📒 分账本管理更自由",
howto_feature1_text: "不同目标建立不同账本，每个年龄层都适用。分开管理更清楚，人生目标井然有序。",
howto_feature2_title: "📈 复利成长模拟",
howto_feature2_text: "输入初始金额、报酬率与定期投入金额，模拟资产在时间推动下的成长潜力，提早看到未来。",
howto_feature3_title: "💰 资产整合与币别换算",
howto_feature3_text: "整合 ETF、基金、股票、保单、加密货币、现金与房产，自动计算总市值与盈余，并支持台币换算。",
howto_feature4_title: "⏳ 退休提领与风险试算",
howto_feature4_text: "依据目前资产与提领设定模拟退休现金流，帮你看见“可以支撑多久”的未来画面，做出有感决策。",
howto_feature5_title: "🧯 紧急预备金试算工具",
howto_feature5_text: "输入生活支出项目（如房租、食物、育儿），自动试算应准备的 3～6 个月紧急预备金金额，打造安全缓冲区。",
howto_feature6_title: "🔐 云端同步 + Google 安全登录",
howto_feature6_text: "一键登录、自动保存至云端，支持多账本、多设备同步操作，资料仅属于你，无干扰、无压力。",
howto_cta: "立即开始使用",
howto_conclusion: "好好存，不只是记账，而是你在为未来财务留下安全、自由与不慌张的底气。",
privacy_title: "隐私权政策",
privacy_intro: "FINORA｜好好存，尊重并保护使用者的个人资料。以下是我们如何收集、使用及保护您的信息。",
privacy_section1: "一、收集信息",
privacy_content1: "我们仅会在用户自愿提供的情况下收集姓名、Email 等信息。Google 登录仅用于个人资料同步，不作其他用途。",
privacy_section2: "二、资料用途",
privacy_content2: "收集的资料仅用于账本同步、功能使用分析与产品改进，不会出售或提供给第三方。",
privacy_section3: "三、资料储存与安全",
privacy_content3: "所有资料均储存在 Google Firebase Cloud，采用标准化加密与身份验证保护。",
privacy_section4: "四、用户权利",
privacy_content4: "用户可随时删除账本内容与个人资料。如需删除账户，请联系我们。",
privacy_section5: "五、政策更新",
privacy_content5: "我们将根据需要更新隐私政策。更新后将在本页公布，重大变更将另行通知用户。",
privacy_start: "立即开始使用",
    compound_title: "复利试算｜FINORA",
    compound_intro: "🔢 输入起始金额、年报酬率与时间，模拟复利增长效果",
    currency_label: "资产总市值币别：",
    total_asset_loading: "💰 资产加总读取中...",
    total_asset_value: "💰 当前资产总市值（折合 {currency}）：",
    fetching_exchange: "📡 查询最新汇率中...",
    invalid_exchange: "无效汇率资料",
    exchange_updated: "✅ 汇率更新完成",
    using_stored_exchange: "⚠️ 使用上次储存的汇率资料",
    using_default_exchange: "⚠️ 使用默认汇率资料",
    exchange_not_ready: "⚠️ 汇率尚未就绪，无法显示市值",
    no_assets: "⚠️ 尚未登记任何资产",
    compound_result_prefix: "投入 {years} 年后，期末总资产约为 ",
    unit_currency: "元",
    asset_category_summary: "📊 资产分类汇总：",
    currency_totals: "💱 币别总市值：",
    user: "使用者",
    account_book: "账本",
    last_calculated: "🛎 最近一次试算结果约为",
    please_login: "请先登入后再使用此功能",
    no_account_warning: "⚠️ 找不到任何账本，请先回首页建立账本",
    back_home_link: "← 返回首页",
    footer_guide: "使用说明",
    footer_contact: "联系我们",
    footer_privacy: "隐私权条款",
    footer_copyright: "© 2025 FINORA 好好存｜家庭友善资产整合工具",
   label_principal: "初始投入金额（元）：",
label_rate: "年回报率（%）：",
label_years: "投资年数：",
label_annual: "每年定期投入金额：",
label_monthly: "每月定期投入金额：",
compound_input_title: "📈 复利试算",
calculate_button: "计算复利",
last_calculated: "上次试算结果：",
   exchange_tool: "汇率换算",
label_amount: "金额：",
label_from: "从：",
label_to: "转换为：",
convert_button: "换算",
exchange_updated: "✅ 汇率更新完成",
   type_股票: "股票",
type_基金: "基金",
type_加密貨幣: "加密货币",
type_儲蓄保險: "储蓄保险",
type_現金: "现金",
type_房產: "房产",
type_定存: "定存",
type_其他: "其他", 

},

"en": {
  title: "FINORA Wealth Planner",
  subtitle: "Make your assets powerful. Retire without worries.",
  asset: "Asset Manager",
  compound: "Compound Calculator",
  withdraw: "Withdrawal Planner",
  emergency: "Emergency Fund",
  accountLabel: "Select Account:",
  rename: "✏️ Rename",
  add: "➕ Add Account",
  delete: "🗑️ Delete Account",
  save: "Save",
  login: "🔐 Sign in with Google",
  logout: "🚪 Sign Out",
  langLabel: "🌐 Language:",
  privacy: "FINORA values your privacy. Your data is yours only.",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA Wealth｜Family-friendly asset organizer",
  guide: "User Guide",
  contact: "Contact Us",
  policy: "Privacy Policy",
  placeholderNewAccount: "Enter new account name",
  asset_title: "Register Your Wealth Assets",
  guide_select_type: "📢 Select asset type below (e.g., Stocks, Insurance, Crypto)",
  guide_stock_auto: "💾 US and TW stocks will fetch real-time price automatically",
  guide_currency_auto: "🔗 Exchange rate will be auto-filled for foreign currencies",
  save_btn: "💾 Save Asset",
  asset_list: "Asset List",
  asset_total: "Total Assets",
  back_to_home: "← Back to Home",
  privacy_note: "🔐 All data is saved to your Google account and cloud ledger securely.",
  user: "User:",
  account: "Account:",
  label_type: "Type:",
  label_name: "Name:",
  label_amount: "Amount:",
  label_currency: "Currency:",
  label_bank: "Bank:",
  label_note: "Note:",
  label_display_currency: "💱 Display currency for total assets:",
  option_please_select: "Please select",
  option_stock: "Stock",
  option_deposit: "Deposit",
  option_cash: "Cash",
  option_property: "Property",
  option_insurance: "Insurance",
  option_fund: "Fund",
  option_crypto: "Cryptocurrency",
  option_other: "Other",
  option_股票: "Stock",
  option_定存: "Deposit",
  option_現金: "Cash",
  option_房產: "Property",
  option_儲蓄保險: "Insurance",
  option_基金: "Fund",
  option_加密貨幣: "Cryptocurrency",
  option_其他: "Other",
  footer_help: "User Guide",
  footer_contact: "Contact Us",
  footer_privacy: "Privacy Policy",
  not_logged_in: "(Not logged in)",
  no_account_selected: "(No account selected)",
  please_login_first: "⚠️ Not logged in. Please sign in with your Google account first.",
  init_error: "System initialization error. Please refresh the page.",
  total_asset: "Total Assets",
  exchange_rate_updated: "Exchange Rate Updated",
  cost: "Cost",
  current_price: "Current Price",
  market_value: "Market Value",
  profit: "Profit",
  option_select: "Please select",
  save_asset: "Save Asset",
howto_title: "User Guide",
howto_intro: "An asset integration tool for individuals, families, and freelancers to stay financially clear—and guide kids to money awareness.",
howto_feature1_title: "📒 Flexible Ledger Management",
howto_feature1_text: "Create separate accounts for different goals, suitable for all ages. Manage separately to see clearly and plan orderly.",
howto_feature2_title: "📈 Compound Growth Simulator",
howto_feature2_text: "Enter starting amount, return rate, and regular investments to simulate future asset growth powered by time.",
howto_feature3_title: "💰 Asset Integration & Currency Conversion",
howto_feature3_text: "Combine ETFs, funds, stocks, insurance, crypto, cash, and property. Automatically calculate market value and profit in TWD.",
howto_feature4_title: "⏳ Retirement Withdrawal & Risk Planner",
howto_feature4_text: "Based on your current assets and withdrawal setup, simulate retirement cash flow and see how long your money may last.",
howto_feature5_title: "🧯 Emergency Fund Estimator",
howto_feature5_text: "Enter living expenses (e.g., rent, food, childcare) to estimate how much to save for 3–6 months of emergency support.",
howto_feature6_title: "🔐 Cloud Sync + Secure Google Login",
howto_feature6_text: "One-click login and cloud storage with multi-ledger, multi-device sync. Your data belongs to you—free of ads or pressure.",
howto_cta: "Start Using Now",
howto_conclusion: "FINORA isn't just for tracking—it's your calm, secure, and free future in the making.",
privacy_title: "Privacy Policy",
privacy_intro: "FINORA respects and protects your personal data. Here's how we collect, use, and secure your information.",
privacy_section1: "1. Data Collection",
privacy_content1: "We only collect your name and email when voluntarily provided. Google Sign-In is solely used for syncing personal data.",
privacy_section2: "2. Purpose of Use",
privacy_content2: "The collected data is used for syncing accounts, usage analysis, and product improvement. It will not be sold or shared with third parties.",
privacy_section3: "3. Data Storage & Security",
privacy_content3: "All data is stored on Google Firebase Cloud with standard encryption and authentication protocols.",
privacy_section4: "4. Your Rights",
privacy_content4: "You may delete your data and accounts at any time. Please contact us if you wish to remove your entire account.",
privacy_section5: "5. Policy Updates",
privacy_content5: "We may update this policy as needed. Major updates will be announced separately and published here.",
privacy_start: "Start Using Now",
  compound_title: "Compound Calculator｜FINORA",
    compound_intro: "🔢 Enter initial amount, annual return and time to simulate compound growth",
    currency_label: "Asset Value Currency:",
    total_asset_loading: "💰 Loading total assets...",
    total_asset_value: "💰 Current total asset value (in {currency}): ",
    fetching_exchange: "📡 Fetching latest exchange rates...",
    invalid_exchange: "Invalid exchange data",
    exchange_updated: "✅ Exchange rates updated",
    using_stored_exchange: "⚠️ Using previously stored exchange data",
    using_default_exchange: "⚠️ Using default exchange rates",
    exchange_not_ready: "⚠️ Exchange rates not ready, cannot display value",
    no_assets: "⚠️ No assets recorded yet",
    compound_result_prefix: "After {years} years, the estimated total is ",
    unit_currency: "NTD",
    asset_category_summary: "📊 Asset Category Summary:",
    currency_totals: "💱 Currency Totals:",
    user: "User",
    account_book: "Account Book",
    last_calculated: "🛎 Last calculated result:",
    please_login: "Please log in to use this feature",
    no_account_warning: "⚠️ No account book found. Please create one on the homepage first.",
    back_home_link: "← Back to Home",
    footer_guide: "How to Use",
    footer_contact: "Contact Us",
    footer_privacy: "Privacy Policy",
    footer_copyright: "© 2025 FINORA｜A family-friendly asset management tool",
  label_principal: "Initial Investment (NTD):",
label_rate: "Annual Return Rate (%):",
label_years: "Investment Years:",
label_annual: "Annual Regular Investment:",
label_monthly: "Monthly Regular Investment:",
compound_input_title: "📈 Compound Calculator",
calculate_button: "Calculate Compound",
last_calculated: "Last calculated:",
  exchange_tool: "Exchange Rate Converter",
label_amount: "Amount:",
label_from: "From:",
label_to: "To:",
convert_button: "Convert",
exchange_updated: "✅ Exchange rates updated",
  type_股票: "Stocks",
type_基金: "Funds",
type_加密貨幣: "Crypto",
type_儲蓄保險: "Insurance",
type_現金: "Cash",
type_房產: "Real Estate",
type_定存: "Fixed Deposit",
type_其他: "Other", 

},
  
 "ja": {
  title: "FINORA 資産管理",
  subtitle: "資産を強く、安心なリタイアへ。",
  asset: "資産管理",
  compound: "複利計算",
  withdraw: "引き出し計画",
  emergency: "緊急資金",
  accountLabel: "帳簿の選択：",
  rename: "✏️ 名前を変更",
  add: "➕ 帳簿を追加",
  delete: "🗑️ 削除",
  save: "保存",
  login: "🔐 Googleでログイン",
  logout: "🚪 ログアウト",
  langLabel: "🌐 言語：",
  privacy: "FINORAはあなたのプライバシーを尊重します。資産はあなただけのものです。",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA 資産管理｜家族向けの資産統合ツール",
  guide: "使用方法",
  contact: "お問い合わせ",
  policy: "プライバシーポリシー",
  placeholderNewAccount: "新しい帳簿名を入力",
  asset_title: "資産を登録する",
  guide_select_type: "📢 下のメニューから資産の種類を選んでください（株、保険、暗号通貨など）",
  guide_stock_auto: "💾 米国株の現在価格は自動取得されます",
  guide_currency_auto: "🔗 外貨資産は最新の為替レートが自動入力されます",
  save_btn: "💾 資産を保存する",
  asset_list: "資産リスト",
  asset_total: "資産合計",
  back_to_home: "← ホームへ戻る",
  privacy_note: "🔐 データはすべてあなたのGoogleアカウントとクラウドに安全に保存されます。",
  user: "ユーザー：",
  account: "帳簿：",
  label_type: "種類：",
  label_name: "名称：",
  label_amount: "金額：",
  label_currency: "通貨：",
  label_bank: "銀行名：",
  label_note: "備考：",
  label_display_currency: "💱 総資産の表示通貨：",
  option_please_select: "選択してください",
  option_stock: "株式",
  option_deposit: "定期預金",
  option_cash: "現金",
  option_property: "不動産",
  option_insurance: "保険",
  option_fund: "投資信託",
  option_crypto: "暗号通貨",
  option_other: "その他",
  option_股票: "株式",
  option_定存: "定期預金",
  option_現金: "現金",
  option_房產: "不動産",
  option_儲蓄保險: "保険",
  option_基金: "投資信託",
  option_加密貨幣: "暗号通貨",
  option_其他: "その他",
  footer_help: "使用方法",
  footer_contact: "お問い合わせ",
  footer_privacy: "プライバシーポリシー",
  not_logged_in: "（未ログイン）",
  no_account_selected: "（アカウント未選択）",
  please_login_first: "⚠️ 未ログインです。まず Google アカウントにログインしてください。",
  init_error: "システム初期化エラー。ページを再読み込みしてください。",
  total_asset: "資産合計",
  exchange_rate_updated: "為替レート更新時間",
  cost: "取得価格",
  current_price: "現在価格",
  market_value: "評価額",
  profit: "利益",
   option_select: "選択してください",
save_asset: "資産を保存する",
   howto_title: "使い方ガイド",
howto_intro: "個人、家族、フリーランスのために設計された資産統合ツール。財務状況を把握し、子どもと一緒にお金の感覚を育む。",
howto_feature1_title: "📒 帳簿を分けて自由に管理",
howto_feature1_text: "目的ごとに帳簿を分けて管理。年齢を問わず使いやすく、人生の目標が見えやすくなります。",
howto_feature2_title: "📈 複利成長シミュレーション",
howto_feature2_text: "初期金額・利回り・定期投入を入力し、時間とともに資産がどのように増えるかを可視化。",
howto_feature3_title: "💰 資産統合と通貨換算",
howto_feature3_text: "ETF、ファンド、株、保険、暗号通貨、現金、不動産を統合して、時価と利益を自動計算。TWD換算にも対応。",
howto_feature4_title: "⏳ 退職後の引き出しとリスク試算",
howto_feature4_text: "現在の資産と引き出し設定に基づき、老後のキャッシュフローをシミュレート。将来の安心を可視化します。",
howto_feature5_title: "🧯 緊急資金の試算ツール",
howto_feature5_text: "生活費（家賃・食費・育児など）を入力し、3〜6か月分の必要な緊急資金額を自動試算。安心のクッションを作成。",
howto_feature6_title: "🔐 クラウド同期 + Google安全ログイン",
howto_feature6_text: "ワンクリックでログイン＆クラウド保存。複数の帳簿・デバイスで同期可能。広告なし、安心の個人管理。",
howto_cta: "今すぐ使い始める",
howto_conclusion: "「好好存」はただの記帳ではなく、未来の自由と安心をあなたに届ける財務基盤です。",
privacy_title: "プライバシーポリシー",
privacy_intro: "FINORA｜好好存は、ユーザーの個人情報を尊重し、保護します。以下に、情報の収集、利用、保護について説明します。",
privacy_section1: "1. 情報の収集",
privacy_content1: "ユーザーが自発的に提供する場合に限り、氏名やメールアドレスなどの情報を収集します。Google ログインはデータ同期のみに使用されます。",
privacy_section2: "2. 利用目的",
privacy_content2: "収集した情報は帳簿同期、機能分析、製品改善のみに使用され、第三者に提供・販売されることはありません。",
privacy_section3: "3. データの保存とセキュリティ",
privacy_content3: "すべてのデータは Google Firebase Cloud に保存され、暗号化と認証により保護されています。",
privacy_section4: "4. ユーザーの権利",
privacy_content4: "ユーザーは帳簿や個人情報をいつでも削除できます。アカウント削除を希望する場合はご連絡ください。",
privacy_section5: "5. ポリシーの更新",
privacy_content5: "必要に応じてポリシーを更新します。重大な変更は別途通知し、本ページに掲載します。",
privacy_start: "今すぐ始める",
    compound_title: "複利計算｜FINORA",
    compound_intro: "🔢 初期金額、年利回り、期間を入力して複利成長をシミュレーション",
    currency_label: "資産総額の通貨：",
    total_asset_loading: "💰 資産合計を読み込み中...",
    total_asset_value: "💰 現在の資産総額（{currency} 換算）：",
    fetching_exchange: "📡 最新の為替レートを取得中...",
    invalid_exchange: "無効な為替データです",
    exchange_updated: "✅ 為替レート更新完了",
    using_stored_exchange: "⚠️ 保存された為替データを使用中",
    using_default_exchange: "⚠️ デフォルトの為替レートを使用中",
    exchange_not_ready: "⚠️ 為替レートが未取得のため表示不可",
    no_assets: "⚠️ 登録された資産がありません",
    compound_result_prefix: "{years} 年後の合計資産：約 ",
    unit_currency: "円",
    asset_category_summary: "📊 資産カテゴリ別合計：",
    currency_totals: "💱 通貨別合計：",
    user: "ユーザー",
    account_book: "帳簿",
    last_calculated: "🛎 前回の試算結果：約",
    please_login: "この機能を使用するにはログインしてください",
    no_account_warning: "⚠️ 帳簿が見つかりません。ホームページで作成してください。",
    back_home_link: "← ホームに戻る",
    footer_guide: "使い方",
    footer_contact: "お問い合わせ",
    footer_privacy: "プライバシーポリシー",
    footer_copyright: "© 2025 FINORA｜家族向けの資産統合ツール",
   label_principal: "初期投資金額（元）：",
label_rate: "年利回り（%）：",
label_years: "投資年数：",
label_annual: "年間定期投資額：",
label_monthly: "毎月定期投資額：",
compound_input_title: "📈 複利計算",
calculate_button: "複利を計算",
last_calculated: "前回の計算結果：",
   exchange_tool: "為替換算",
label_amount: "金額：",
label_from: "から：",
label_to: "へ：",
convert_button: "換算",
exchange_updated: "✅ 為替レート更新完了",
   type_股票: "株式",
type_基金: "ファンド",
type_加密貨幣: "暗号資産",
type_儲蓄保險: "保険",
type_現金: "現金",
type_房產: "不動産",
type_定存: "定期預金",
type_其他: "その他", 
   
  }
};

