const translations = {
  "zh-Hant": {
    title: "FINORA 好好存",
    subtitle: "讓資產更有力，退休不焦慮。",
    asset: "資產管理",
    compound: "複利試算",
    withdraw: "退休提領",
    emergency: "預備金試算",
    accountLabel: "帳本選擇：",
    rename: "✏️ 重新命名",
    add: "➕ 新增帳本",
    delete: "🗑️ 刪除帳本",
    save: "儲存",
    login: "🔐 使用 Google 帳號登入",
    logout: "🚪 登出",
    langLabel: "🌐 語言：",
    privacy: "FINORA 重視隱私。你的資產，只屬於你自己。",
    version: "v0.9 beta - 2025-06-04",
    footer: "© 2025 FINORA 好好存｜家庭友善資產整合工具",
    guide: "使用說明",
    contact: "聯絡我們",
    policy: "隱私權條款",
    placeholderNewAccount: "輸入新帳本名稱",
    asset_title: "登記你的好好資產",
    guide_select_type: "📢 從下方選單挑選資產種類（股票、保單、加密貨幣等）",
    guide_stock_auto: "🪙 台股與美股會自動查詢最新現價",
    guide_currency_auto: "🔗 輸入外幣資產時，系統會自動帶入最新匯率",
    save_btn: "💾 儲存資產",
    asset_list: "資產列表",
    asset_total: "資產加總",
    back_to_home: "← 返回首頁",
    privacy_note: "🔐 所有資料皆保存在你的 Google 帳號與雲端帳本中，不用擔心遺失或外洩。",
    user: "使用者：",
    account: "帳本：",
    label_type: "種類：",
    label_name: "名稱：",
    label_amount: "金額：",
    label_currency: "幣別：",
    label_bank: "銀行名稱：",
    label_note: "備註：",
    option_please_select: "請選擇",
    option_stock: "股票",
    option_deposit: "定存",
    option_cash: "現金",
    option_property: "房產",
    option_insurance: "儲蓄保險",
    option_fund: "基金",
    option_crypto: "加密貨幣",
    option_other: "其他"
  },
  "zh-Hans": {
    title: "FINORA 好好存",
    subtitle: "让资产更有力，退休不焦虑。",
    asset: "资产管理",
    compound: "复利试算",
    withdraw: "退休提领",
    emergency: "预备金试算",
    accountLabel: "账本选择：",
    rename: "✏️ 重命名",
    add: "➕ 新增账本",
    delete: "🗑️ 删除账本",
    save: "保存",
    login: "🔐 使用 Google 账号登入",
    logout: "🚪 登出",
    langLabel: "🌐 语言：",
    privacy: "FINORA 重视隐私。你的资产，只属于你自己。",
    version: "v0.9 beta - 2025-06-04",
    footer: "© 2025 FINORA 好好存｜家庭友善资产整合工具",
    guide: "使用说明",
    contact: "联系我们",
    policy: "隐私条款",
    placeholderNewAccount: "输入新账本名称",
    asset_title: "登记你的好好资产",
    guide_select_type: "📢 从下方选单挑选资产种类（股票、保单、加密货币等）",
    guide_stock_auto: "🪙 台股与美股会自动查询最新现价",
    guide_currency_auto: "🔗 输入外币资产时，系统会自动带入最新汇率",
    save_btn: "💾 保存资产",
    asset_list: "资产列表",
    asset_total: "资产总计",
    back_to_home: "← 返回首页",
    privacy_note: "🔐 所有资料皆保存在你的 Google 帐号与云端账本中，无需担心遗失或外泄。",
    user: "使用者：",
    account: "账本：",
    label_type: "种类：",
    label_name: "名称：",
    label_amount: "金额：",
    label_currency: "币别：",
    label_bank: "银行名称：",
    label_note: "备注：",
    option_please_select: "请选择",
    option_stock: "股票",
    option_deposit: "定存",
    option_cash: "现金",
    option_property: "房产",
    option_insurance: "储蓄保险",
    option_fund: "基金",
    option_crypto: "加密货币",
    option_other: "其他"
  },
  "en": {
    title: "FINORA Wealth Planner",
    subtitle: "Make your assets powerful. Retire without worries.",
    asset: "Asset Manager",
    compound: "Compound Calculator",
    withdraw: "Withdrawal Planner",
    emergency: "Emergency Fund",
    accountLabel: "Select Account:",
    rename: "✏️ Rename",
    add: "➕ Add Account",
    delete: "🗑️ Delete Account",
    save: "Save",
    login: "🔐 Sign in with Google",
    logout: "🚪 Sign Out",
    langLabel: "🌐 Language:",
    privacy: "FINORA values your privacy. Your data is yours only.",
    version: "v0.9 beta - 2025-06-04",
    footer: "© 2025 FINORA Wealth｜Family-friendly asset organizer",
    guide: "User Guide",
    contact: "Contact Us",
    policy: "Privacy Policy",
    placeholderNewAccount: "Enter new account name",
    asset_title: "Register Your Wealth Assets",
    guide_select_type: "📢 Select asset type below (e.g., Stocks, Insurance, Crypto)",
    guide_stock_auto: "🪙 US and TW stocks will fetch real-time price automatically",
    guide_currency_auto: "🔗 Exchange rate will be auto-filled for foreign currencies",
    save_btn: "💾 Save Asset",
    asset_list: "Asset List",
    asset_total: "Total Assets",
    back_to_home: "← Back to Home",
    privacy_note: "🔐 All data is saved to your Google account and cloud ledger securely.",
    user: "User:",
    account: "Account:",
    label_type: "Type:",
    label_name: "Name:",
    label_amount: "Amount:",
    label_currency: "Currency:",
    label_bank: "Bank:",
    label_note: "Note:",
    option_please_select: "Please select",
    option_stock: "Stock",
    option_deposit: "Deposit",
    option_cash: "Cash",
    option_property: "Property",
    option_insurance: "Insurance",
    option_fund: "Fund",
    option_crypto: "Cryptocurrency",
    option_other: "Other"
  },
  "ja": {
    title: "FINORA 資産管理",
    subtitle: "資産を強く、安心なリタイアへ。",
    asset: "資産管理",
    compound: "複利計算",
    withdraw: "引き出し計画",
    emergency: "緊急資金",
    accountLabel: "帳簿の選択：",
    rename: "✏️ 名前を変更",
    add: "➕ 帳簿を追加",
    delete: "🗑️ 削除",
    save: "保存",
    login: "🔐 Googleでログイン",
    logout: "🚪 ログアウト",
    langLabel: "🌐 言語：",
    privacy: "FINORAはあなたのプライバシーを尊重します。資産はあなただけのものです。",
    version: "v0.9 beta - 2025-06-04",
    footer: "© 2025 FINORA 資産管理｜家族向けの資産統合ツール",
    guide: "使用方法",
    contact: "お問い合わせ",
    policy: "プライバシーポリシー",
    placeholderNewAccount: "新しい帳簿名を入力",
    asset_title: "資産を登録する",
    guide_select_type: "📢 下のメニューから資産の種類を選んでください（株、保険、暗号通貨など）",
    guide_stock_auto: "🪙 日本株・米国株の現在価格は自動取得されます",
    guide_currency_auto: "🔗 外貨資産は最新の為替レートが自動入力されます",
    save_btn: "💾 資産を保存する",
    asset_list: "資産リスト",
    asset_total: "資産合計",
    back_to_home: "← ホームへ戻る",
    privacy_note: "🔐 データはすべてあなたのGoogleアカウントとクラウドに安全に保存されます。",
    user: "ユーザー：",
    account: "帳簿：",
    label_type: "種類：",
    label_name: "名称：",
    label_amount: "金額：",
    label_currency: "通貨：",
    label_bank: "銀行名：",
    label_note: "備考：",
    option_please_select: "選択してください",
    option_stock: "株式",
    option_deposit: "定期預金",
    option_cash: "現金",
    option_property: "不動産",
    option_insurance: "保険",
    option_fund: "投資信託",
    option_crypto: "暗号通貨",
    option_other: "その他"
  }
};

function applyLang() {
  const lang = localStorage.getItem("lang") || "zh-Hant";
  const dict = translations[lang] || translations["zh-Hant"];
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) el.textContent = dict[key];
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (dict[key]) el.setAttribute("placeholder", dict[key]);
  });
  document.querySelectorAll("[data-i18n-option]").forEach(el => {
    const key = el.getAttribute("data-i18n-option");
    if (dict[key]) el.innerText = dict[key];
  });
}const translations = {
  "zh-Hant": {
    not_logged_in: "（尚未登入）",
    no_account_selected: "（尚未選擇）",
    please_login_first: "⚠️ 尚未登入，請先登入 Google 帳號",
    init_error: "系統初始化錯誤，請重新整理頁面"
  },
  "zh-Hans": {
    not_logged_in: "（尚未登录）",
    no_account_selected: "（尚未选择）",
    please_login_first: "⚠️ 尚未登录，请先登录 Google 账号",
    init_error: "系统初始化错误，请重新刷新页面"
  },
  "en": {
    not_logged_in: "(Not logged in)",
    no_account_selected: "(No account selected)",
    please_login_first: "⚠️ Not logged in. Please sign in with your Google account first.",
    init_error: "System initialization error. Please refresh the page."
  },
  "ja": {
    not_logged_in: "（未ログイン）",
    no_account_selected: "（アカウント未選択）",
    please_login_first: "⚠️ 未ログインです。まず Google アカウントにログインしてください。",
    init_error: "システム初期化エラー。ページを再読み込みしてください。"
  }
};
