// ✅ 多語言模組（整合版）

function i18n(key, vars = {}) {
  const lang = localStorage.getItem("lang") || "zh-Hant";
  let text = translations[lang]?.[key] || key;
  for (const [k, v] of Object.entries(vars)) {
    text = text.replace(`{${k}}`, v);
  }
  return text;
}

function applyLang(lang = localStorage.getItem("lang") || "zh-Hant") {
  const dict = translations[lang] || translations["zh-Hant"];

  // 所有內文元素
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) el.textContent = dict[key];
  });

  // select 選單內的 option
  document.querySelectorAll("option[data-i18n-option]").forEach(opt => {
    const key = opt.getAttribute("data-i18n-option");
    if (dict[key]) opt.textContent = dict[key];
  });

  // input 的 placeholder
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (dict[key]) el.placeholder = dict[key];
  });
}

const translations = {
 "zh-Hant": {
  title: "FINORA 好好存",
  subtitle: "讓資產更有力，退休不焦慮。",
  asset: "資產管理",
  compound: "複利試算",
  withdraw: "退休提領",
  emergency: "預備金試算",
  accountLabel: "帳本選擇：",
  rename: "✏️ 重新命名",
  add: "➕ 新增帳本",
  delete: "🗑️ 刪除帳本",
  save: "儲存",
  login: "🔐 使用 Google 帳號登入",
  logout: "🚪 登出",
  langLabel: "🌐 語言：",
  privacy: "FINORA 重視隱私。你的資產，只屬於你自己。",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA 好好存｜家庭友善資產整合工具",
  guide: "使用說明",
  contact: "聯絡我們",
  policy: "隱私權條款",
  placeholderNewAccount: "輸入新帳本名稱",
  asset_title: "登記你的好好資產",
  guide_select_type: "📢 從下方選單挑選資產種類（股票、保單、加密貨幣等）",
  guide_stock_auto: "💾 台股與美股會自動查詢最新現價",
  guide_currency_auto: "🔗 輸入外幣資產時，系統會自動帶入最新匯率",
  save_btn: "💾 儲存資產",
  asset_list: "資產列表",
  asset_total: "資產加總",
  back_to_home: "← 返回首頁",
  privacy_note: "🔐 所有資料皆保存在你的 Google 帳號與雲端帳本中，不用擔心遺失或外洩。",
  user: "使用者：",
  account: "帳本：",
  label_type: "種類：",
  label_name: "名稱：",
  label_amount: "金額",
  label_currency: "幣別：",
  label_bank: "銀行名稱：",
  label_note: "備註：",
  label_display_currency: "💱 總資產顯示幣別：",
  option_please_select: "請選擇",
  option_stock: "股票",
  option_deposit: "定存",
  option_cash: "現金",
  option_property: "房產",
  option_insurance: "儲蓄保險",
  option_fund: "基金",
  option_crypto: "加密貨幣",
  option_other: "其他",
  option_股票: "股票",
  option_定存: "定存",
  option_現金: "現金",
  option_房產: "房產",
  option_儲蓄保險: "儲蓄保險",
  option_基金: "基金",
  option_加密貨幣: "加密貨幣",
  option_其他: "其他",
  footer_help: "使用說明",
  footer_contact: "聯絡我們",
  footer_privacy: "隱私權條款",
  not_logged_in: "（尚未登入）",
  no_account_selected: "（尚未選擇）",
  please_login_first: "⚠️ 尚未登入，請先登入 Google 帳號",
  init_error: "系統初始化錯誤，請重新整理頁面",
  total_asset: "總資產",
  exchange_rate_updated: "匯率更新時間",
  cost: "成本",
  label_price: "現價",
  market_value: "市值",
  profit: "盈餘",
  option_select: "請選擇",
  save_asset: "儲存資產",
howto_title: "使用說明",
howto_intro: "為自己、家庭與自由工作者打造的資產整合工具，清楚掌握財務現況，也陪孩子練習對錢有方向感。",
howto_feature1_title: "📒 分帳本管理更自由",
howto_feature1_text: "不同目標建立不同帳本，每個年齡層都適用。分開管理更清楚，人生目標井然有序。",
howto_feature2_title: "📈 複利成長模擬",
howto_feature2_text: "輸入初始金額、報酬率與定期投入金額，模擬資產在時間推動下的成長潛力，提早看到未來。",
howto_feature3_title: "💰 資產整合與幣別換算",
howto_feature3_text: "整合 ETF、基金、股票、保單、加密貨幣、現金與房產，自動計算總市值與盈餘，並支援台幣換算。",
howto_feature4_title: "⏳ 退休提領與風險試算",
howto_feature4_text: "依照目前資產與提領設定模擬退休現金流，幫你看見「可以支撐多久」的未來畫面，做出有感決策。",
howto_feature5_title: "🧯 緊急預備金試算工具",
howto_feature5_text: "輸入生活支出項目（如房租、食物、育兒），自動試算應準備的 3～6 個月緊急預備金金額，打造安全緩衝區。",
howto_feature6_title: "🔐 雲端同步 + Google 安全登入",
howto_feature6_text: "一鍵登入、自動儲存至雲端，支援多帳本、多裝置同步操作，資料僅屬於你，無干擾、無壓力。",
howto_cta: "立即開始使用",
howto_conclusion: "好好存，不只是記帳，而是你在為未來財務留下安全、自由與不慌張的底氣。",
privacy_title: "隱私權政策",
privacy_intro: "FINORA｜好好存，尊重並保護使用者的個人資料。以下是我們如何蒐集、使用及保護您的資訊。",
privacy_section1: "一、蒐集資訊",
privacy_content1: "我們僅會在使用者自願提供的情況下收集姓名、Email 等資訊。Google 登入僅用於個人資料同步，不會另作其他用途。",
privacy_section2: "二、資料用途",
privacy_content2: "收集的資料將僅用於帳本同步、功能使用分析與產品改善，不會出售或提供給第三方。",
privacy_section3: "三、資料儲存與安全",
privacy_content3: "所有資料均儲存在 Google Firebase Cloud，採用標準化加密與身份驗證保護。",
privacy_section4: "四、使用者權益",
privacy_content4: "使用者可隨時刪除帳本內容與個人資料。如欲刪除帳號，請來信聯絡我們。",
privacy_section5: "五、政策更新",
privacy_content5: "我們將視需求更新隱私政策。更新後將公佈於本頁，重大變更將另行通知使用者。",
privacy_start: "立即開始使用",
   compound_title: "模擬好好未來",
    compound_intro: "🔢 輸入起始金額、年報酬率與時間，模擬複利增值的成長效果",
    compound_input_title: "📈 複利試算",
    label_principal: "初始投入金額（元）：",
    label_rate: "年報酬率（%）：",
    label_years: "投資年數：",
    label_annual: "每年定期投入金額：",
    label_monthly: "每月定期投入金額：",
    calculate_button: "計算複利",
    exchange_tool: "💱 匯率換算",
    label_amount: "金額",
    label_from: "從：",
    label_to: "轉換為：",
    convert_button: "換算",
    currency_label: "資產總市值幣別：",
    total_asset_loading: "💰 資產加總讀取中...",
    total_asset_value: "💰 折合資產總市值：",
    last_calculated: "📌 上次試算結果：",
    fetching_exchange: "正在查詢匯率...",
    invalid_exchange: "取得匯率失敗",
    exchange_updated: "匯率已更新",
    using_stored_exchange: "使用本地備份匯率",
    using_default_exchange: "使用預設匯率",
    exchange_not_ready: "⚠️ 匯率尚未準備好",
    no_assets: "尚未有資產紀錄",
    asset_category_summary: "📊 資產分類加總",
    currency_totals: "💰 各幣別市值加總",
    user: "使用者",
    account_book: "帳本",
    please_login: "請先登入後再使用此功能",
    no_account_warning: "尚未建立任何帳本，請先回首頁新增帳本",
    please_create_account_book: "請先新增帳本後使用工具功能",
    back_home_link: "← 返回首頁",
    unit_currency: "元",
    compound_result_prefix: " {years}年後預估總資產為：",
   label_principal: "初始投入金額（元）：",
label_rate: "年報酬率（%）：",
label_years: "投資年數：",
label_annual: "每年定期投入金額：",
label_monthly_money: "每月定期投入金額：",
compound_input_title: "📈 複利試算",
calculate_button: "計算複利",
last_calculated: "上次試算結果：",
   exchange_tool: "匯率換算",
label_amount: "金額：",
label_from: "從：",
label_to: "轉換為：",
convert_button: "換算",
exchange_updated: "✅ 匯率更新完成",
   type_股票: "股票",
type_基金: "基金",
type_加密貨幣: "加密貨幣",
type_儲蓄保險: "儲蓄保險",
type_現金: "現金",
type_房產: "房產",
type_定存: "定存",
type_其他: "其他",
    title: "FINORA 好好存",
    emergency_title: "緊急預備金試算",
    emergency_intro: "📝 輸入每月固定收入與支出，建立財務護城河",
    account_label: "目前帳本：",
    add_income: "新增收入項目",
    add_expense: "新增支出項目",
    income_item: "收入項目",
    expense_item: "支出項目",
    amount: "金額",
    monthly_income: "每月收入登記",
    monthly_expense: "每月支出登記",
    reserve_calc: "預備金建議試算",
    select_months_label: "選擇涵蓋月數：",
    months_option_3: "3 個月",
    months_option_6: "6 個月",
    months_option_9: "9 個月",
    months_option_12: "12 個月",
    monthly_income_total: "每月收入總計",
    monthly_expense_total: "每月支出總計",
   suggested_reserve: "建議預備金",
    currency_unit: "元",
    no_account_selected_alert: "尚未選擇帳本，請先回首頁登入並選擇帳本！",
    back_home_link: "← 返回首頁",
    footer_guide: "使用說明",
    footer_contact: "聯絡我們",
    footer_privacy: "隱私權條款",
    footer_copyright: "© 2025 FINORA 好好存｜家庭友善資產整合工具",
   withdraw_title: "退休提領試算｜FINORA",
    withdraw_heading: "退休金怎麼花",
    withdraw_intro: "💶 輸入預估資產、提領金額或比率，可加入年報酬率與通膨率",
    label_total: "預估資產總額（元）：",
    label_monthly: "每月提領金額（元）：",
    label_withdraw_rate: "提領比率（％）：",
    label_return_rate: "年報酬率（％）：",
    label_inflation_rate: "年通膨率（％）：",
    placeholder_monthly: "預設 30,000",
    btn_toggle_inflation: "💡 每年提領金額根據通膨調整",
    btn_calculate: "試算",
    basic_withdraw: "一般月領試算",
    can_last: "可支撐約",
    years: "年",
    months: "個月",
    withdraw_rate_method: "提領法", 
    yearly: "每年約",
    monthly: "每月約",
    estimated_duration: "預估可支撐",
    real_rate_calc: "報酬與通膨調整",
    real_rate: "實質年報酬率約為",
    inflation_adjusted_withdraw_simulation: "通膨保值提領模擬",
    default_monthly_warn: "⚠️ 未輸入預估月提領金額，預設從 NT$30,000 起算",
    year: "第",
    yearly_out: "年支出",
    remaining_asset: "剩餘資產",
    withdraw_until_year: "預估可提領至第",
    inflation_enabled: "已啟用通膨調整",
    inflation_disabled: "每年提領金額根據通膨調整",
    please_login_first: "請先登入後再使用此功能",
    recent_compound_result: "最近一次複利結果",
// 📌 提領說明區塊
section_explanation_title: "📌 提領方式說明：",

method_basic: "一般月領：總資產 ÷ 每月需求 = 可支撐年數。",
method_4percent: "4%法則：每年提領 4%以下，資產理想可撐 30 年以上。",
method_real_rate: "報酬－通膨：年報酬與通膨比較後，提供實質購買力試算。", 
method_adjust_inflation: "通膨調整提領：模擬購買力保值，每年提領金額隨通膨上升。",

btn_explain_more: "📖 什麼是通膨保值提領？",

explain_why: "為什麼要通膨調整？",
explain_reason: "每年的物價會慢慢上漲，如果每月都提一樣的金額，實際能買的東西會越來越少。",
explain_how: "怎麼做？",

step_1: "第一年每月提 30,000 元",
step_2: "通膨 2%，第二年提 30,600 元",
step_3: "第三年提 31,212 元… 以此類推",
   nav_about: "品牌故事",
nav_books: "推薦書單",
   about_title: "品牌故事｜FINORA 好好存",
  about_heading: "FINORA的由來",
  about_p1: "哈嘍，你是否和我一樣，雖然收入穩定，但是對龐大的開銷，資產盤點和未來退休財務狀況感到格外焦慮？",
  about_p2: "透過資產紀錄、報酬試算、退休預估和緊急備用金準備，我漸漸掌握自己的財務狀況。",
  about_p3: "但資產分散在不同銀行和平台，甚至還有不同幣別。每次盤點都要打開一堆 App，Excel 表也難以在手機上使用。",
  about_p4: "我相信，複利最重要的成本，是你願意投入的時間。而財務安全感，是可以一步步存出來的。所以「FINORA 好好存」，一個屬於我們的資產管理工具誕生了。",
  about_p5: "歡迎你加入我們，一起「好好存、好好生活」。",
  back_to_home: "← 回首頁",
unit_share: "股",
   current_account: "目前帳本：",
loading: "讀取中...",
placeholder_monthly: "預設 30,000",
   label_policy_name: "保單名稱",
insured_amount: "保額",
insured_years: "年期",
annual_premium: "年繳",
label_bank: "銀行名稱",
label_note: "備註",
label_fund_name: "基金名稱",
label_fund_units: "單位數",
label_fund_nav: "淨值",
label_crypto_symbol: "幣種",
label_crypto_amount: "數量",
label_crypto_price: "現價",
total: "總金額",
free_user_limit_accounts: "目前為免費帳號，僅能使用一個帳本與基本功能，如需更多功能請升級",
upgrade_required_msg: "您目前使用的是免費帳號 僅限一個帳本與基本功能 如需解鎖更多功能 請升級為進階版",
  upgrade_now: "立即升級",
  close: "關閉",
   login_success: "登入成功！",
    login_failed: "登入失敗，請稍後再試。",
    logout_success: "已成功登出。",
    rename_prompt: "請輸入新的帳本名稱：",
    rename_success: "帳本已重新命名！",
    add_success: "帳本新增成功！",
    delete_success: "帳本已刪除！",
    confirm_delete: "確定要刪除此帳本？",
    account_name_required: "請輸入帳本名稱",
  exchange_rate_error: "匯率查詢錯誤",
using_backup_rates: "使用備援匯率資料（localStorage）",
using_default_rates: "使用預設匯率資料",
exchange_rate_updated: "匯率已更新",
   label_property_name: "房產名稱",
label_property_value: "估值（市價）",
label_mortgage_balance: "房貸餘額",
label_interest_rate: "利率（%）",
label_years_remaining: "剩餘年限",
   unit_years:"年",
   delete_title: "刪除帳號與資料",
delete_intro: "您可以依照下列步驟，要求刪除您的帳號與相關資料。",
delete_steps: "請透過電子郵件聯絡我們，標題請註明：刪除帳號。我們將在收到您的請求後 7 個工作天內處理並回覆確認。",
delete_note: "如需更多協助，請聯絡 service@finora.life",
   footer_delete_account: "刪除帳號",
   footer_terms: "服務條款",
    terms_title: "服務條款",
    terms_intro: "歡迎使用 FINORA 好好存。本服務條款說明您與本平台間的權利與義務。",
    terms_use: "1. 使用者責任：請確認您提供的資料正確且不涉及非法行為。",
    terms_privacy: "2. 隱私保護：我們依據隱私權條款保護您提供的資料。",
    terms_liability: "3. 平台責任：本平台不對資料準確性或使用結果負完全責任。",
    terms_change: "4. 條款變更：我們保留隨時修改條款的權利，請定期查閱。",
    terms_contact: "若您對服務條款有任何疑問，歡迎透過聯絡我們頁面與我們聯繫。",
      no_asset_warning_console: "找不到資產分類資料，請先到資產頁建立資產",
    no_asset_warning_html: "尚未建立資產，請先至資產頁新增資產",
    missing_container_error: "缺少 #asset-summary 容器"
},
  
 "zh-Hans": {
  title: "FINORA 好好存",
  subtitle: "让资产更有力，退休不焦虑。",
  asset: "资产管理",
  compound: "复利试算",
  withdraw: "退休提领",
  emergency: "预备金试算",
  accountLabel: "账本选择：",
  rename: "✏️ 重命名",
  add: "➕ 新增账本",
  delete: "🗑️ 删除账本",
  save: "保存",
  login: "🔐 使用 Google 账号登入",
  logout: "🚪 登出",
  langLabel: "🌐 语言：",
  privacy: "FINORA 重视隐私。你的资产，只属于你自己。",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA 好好存｜家庭友善资产整合工具",
  guide: "使用说明",
  contact: "联系我们",
  policy: "隐私条款",
  placeholderNewAccount: "输入新账本名称",
  asset_title: "登记你的好好资产",
  guide_select_type: "📢 从下方选单挑选资产种类（股票、保单、加密货币等）",
  guide_stock_auto: "💾 台股与美股会自动查询最新现价",
  guide_currency_auto: "🔗 输入外币资产时，系统会自动带入最新汇率",
  save_btn: "💾 保存资产",
  asset_list: "资产列表",
  asset_total: "资产总计",
  back_to_home: "← 返回首页",
  privacy_note: "🔐 所有资料皆保存在你的 Google 帐号与云端账本中，无需担心遗失或外泄。",
  user: "使用者：",
  account: "账本：",
  label_type: "种类：",
  label_name: "名称：",
  label_amount: "金额",
  label_currency: "币别：",
  label_bank: "银行名称：",
  label_note: "备注：",
  label_display_currency: "💱 总资产显示币别：",
  option_please_select: "请选择",
  option_stock: "股票",
  option_deposit: "定存",
  option_cash: "现金",
  option_property: "房产",
  option_insurance: "储蓄保险",
  option_fund: "基金",
  option_crypto: "加密货币",
  option_other: "其他",
  option_股票: "股票",
  option_定存: "定存",
  option_現金: "现金",
  option_房產: "房产",
  option_儲蓄保險: "储蓄保险",
  option_基金: "基金",
  option_加密貨幣: "加密货币",
  option_其他: "其他",
  footer_help: "使用说明",
  footer_contact: "联系我们",
  footer_privacy: "隐私条款",
  not_logged_in: "（尚未登录）",
  no_account_selected: "（尚未选择）",
  please_login_first: "⚠️ 尚未登录，请先登录 Google 账号",
  init_error: "系统初始化错误，请重新刷新页面",
  total_asset: "总资产",
  exchange_rate_updated: "汇率更新时间",
  cost: "成本",
  label_price: "现价",
  market_value: "市值",
  profit: "盈余",
   option_select: "请选择",
save_asset: "保存资产",
   howto_title: "使用说明",
howto_intro: "为自己、家庭与自由工作者打造的资产整合工具，清楚掌握财务现况，也陪孩子练习对钱有方向感。",
howto_feature1_title: "📒 分账本管理更自由",
howto_feature1_text: "不同目标建立不同账本，每个年龄层都适用。分开管理更清楚，人生目标井然有序。",
howto_feature2_title: "📈 复利成长模拟",
howto_feature2_text: "输入初始金额、报酬率与定期投入金额，模拟资产在时间推动下的成长潜力，提早看到未来。",
howto_feature3_title: "💰 资产整合与币别换算",
howto_feature3_text: "整合 ETF、基金、股票、保单、加密货币、现金与房产，自动计算总市值与盈余，并支持台币换算。",
howto_feature4_title: "⏳ 退休提领与风险试算",
howto_feature4_text: "依据目前资产与提领设定模拟退休现金流，帮你看见“可以支撑多久”的未来画面，做出有感决策。",
howto_feature5_title: "🧯 紧急预备金试算工具",
howto_feature5_text: "输入生活支出项目（如房租、食物、育儿），自动试算应准备的 3～6 个月紧急预备金金额，打造安全缓冲区。",
howto_feature6_title: "🔐 云端同步 + Google 安全登录",
howto_feature6_text: "一键登录、自动保存至云端，支持多账本、多设备同步操作，资料仅属于你，无干扰、无压力。",
howto_cta: "立即开始使用",
howto_conclusion: "好好存，不只是记账，而是你在为未来财务留下安全、自由与不慌张的底气。",
privacy_title: "隐私权政策",
privacy_intro: "FINORA｜好好存，尊重并保护使用者的个人资料。以下是我们如何收集、使用及保护您的信息。",
privacy_section1: "一、收集信息",
privacy_content1: "我们仅会在用户自愿提供的情况下收集姓名、Email 等信息。Google 登录仅用于个人资料同步，不作其他用途。",
privacy_section2: "二、资料用途",
privacy_content2: "收集的资料仅用于账本同步、功能使用分析与产品改进，不会出售或提供给第三方。",
privacy_section3: "三、资料储存与安全",
privacy_content3: "所有资料均储存在 Google Firebase Cloud，采用标准化加密与身份验证保护。",
privacy_section4: "四、用户权利",
privacy_content4: "用户可随时删除账本内容与个人资料。如需删除账户，请联系我们。",
privacy_section5: "五、政策更新",
privacy_content5: "我们将根据需要更新隐私政策。更新后将在本页公布，重大变更将另行通知用户。",
privacy_start: "立即开始使用",
     compound_title: "模拟好好未来",
    compound_intro: "🔢 输入起始金额、年报酬率与时间，模拟复利增长的效果",
    compound_input_title: "📈 复利试算",
    label_principal: "初始投入金额（元）：",
    label_rate: "年报酬率（%）：",
    label_years: "投资年数：",
    label_annual: "每年定期投入金额：",
    label_monthly_money: "每月定期投入金额：",
    calculate_button: "计算复利",
    exchange_tool: "💱 汇率换算",
    label_amount: "金额",
    label_from: "从：",
    label_to: "转换为：",
    convert_button : "换算",
    currency_label: "资产总市值币别：",
    total_asset_loading: "💰 资产加总读取中...",
    total_asset_value: "💰 折合资产总市值：",
    last_calculated: "📌 上次试算结果：",
    fetching_exchange: "正在查询汇率...",
    invalid_exchange: "获取汇率失败",
    exchange_updated: "汇率已更新",
    using_stored_exchange: "使用本地备份汇率",
    using_default_exchange: "使用默认汇率",
    exchange_not_ready: "⚠️ 汇率尚未准备好",
    no_assets: "尚无资产记录",
    asset_category_summary: "📊 资产分类加总",
    currency_totals: "💰 各币别市值加总",
    user: "使用者",
    account_book: "账本",
    please_login: "请先登录后再使用此功能",
    no_account_warning: "尚未建立任何账本，请先回首页新增账本",
    please_create_account_book: "请先新增账本后使用工具功能",
    back_home_link: "← 返回首页",
    unit_currency: "元",
    compound_result_prefix: " {years}年后预估总资产为：",
   label_principal: "初始投入金额（元）：",
label_rate: "年回报率（%）：",
label_years: "投资年数：",
label_annual: "每年定期投入金额：",
label_monthly: "每月定期投入金额：",
compound_input_title: "📈 复利试算",
calculate_button: "计算复利",
last_calculated: "上次试算结果：",
   exchange_tool: "汇率换算",
label_amount: "金额：",
label_from: "从：",
label_to: "转换为：",
convert_button: "换算",
exchange_updated: "✅ 汇率更新完成",
   type_股票: "股票",
type_基金: "基金",
type_加密貨幣: "加密货币",
type_儲蓄保險: "储蓄保险",
type_現金: "现金",
type_房產: "房产",
type_定存: "定存",
type_其他: "其他", 
 emergency_title: "紧急预备金试算",
    title: "FINORA 好好存",
    emergency_title: "紧急预备金试算",
    emergency_intro: "📝 输入每月固定收入与支出，建立财务护城河",
    account_label: "当前账本：",
    add_income: "新增收入项目",
    add_expense: "新增支出项目",
    income_item: "收入项目",
    expense_item: "支出项目",
    amount: "金额",
    monthly_income: "每月收入登记",
    monthly_expense: "每月支出登记",
    reserve_calc: "预备金建议试算",
    select_months_label: "选择涵盖月数：",
    months_option_3: "3 个月",
    months_option_6: "6 个月",
    months_option_9: "9 个月",
    months_option_12: "12 个月",
    monthly_income_total: "每月收入总计",
    monthly_expense_total: "每月支出总计",
    suggested_reserve: "建议预备金",
    currency_unit: "元",
    no_account_selected_alert: "尚未选择账本，请先回首页登录并选择账本！",
    back_home_link: "← 返回首页",
    footer_guide: "使用说明",
    footer_contact: "联系我们",
    footer_privacy: "隐私条款",
    footer_copyright: "© 2025 FINORA 好好存｜家庭友善资产整合工具",
   withdraw_title: "退休提领试算｜FINORA",
    withdraw_heading: "退休金怎么花",
    withdraw_intro: "💶 输入预估资产、提领金额或比率，可加入年报酬率与通胀率",
    label_total: "预估资产总额（元）：",
    label_monthly: "每月提领金额（元）：",
    label_withdraw_rate: "提领比率（％）：",
    label_return_rate: "年报酬率（％）：",
    label_inflation_rate: "年通胀率（％）：",
    placeholder_monthly: "默认 30,000",
    btn_toggle_inflation: "💡 每年提领金额根据通胀调整",
    btn_calculate: "试算",
    basic_withdraw: "一般月领试算",
    can_last: "可支撑约",
    years: "年",
    months: "个月",
    withdraw_rate_method: "提领法",
    yearly: "每年约",
    monthly: "每月约",
    estimated_duration: "预估可支撑",
    real_rate_calc: "报酬与通胀调整",
    real_rate: "实际年报酬率约为",
    inflation_adjusted_withdraw_simulation: "通胀保值提领模拟",
    default_monthly_warn: "⚠️ 未输入预估月提领金额，默认从 NT$30,000 起算",
    year: "第",
    yearly_out: "年支出",
    remaining_asset: "剩余资产",
    withdraw_until_year: "预估可提领至第",
    inflation_enabled: "已启用通胀调整",
    inflation_disabled: "每年提领金额根据通胀调整",
    please_login_first: "请先登入后再使用此功能",
    recent_compound_result: "最近一次复利结果",
section_explanation_title: "📌 提领方式说明：",

method_basic: "基本月领：总资产 ÷ 每月需求 = 可支撑年数。",
method_4percent: "4%法则：每年提领 4%以下，资产理想可撑 30 年以上。",
method_real_rate: "报酬－通胀：年报酬与通胀比较后，提供实际购买力试算。",
method_adjust_inflation: "通胀调整提领：模拟购买力保值，每年提领金额随通胀上升。",

btn_explain_more: "📖 什么是通胀保值提领？",

explain_why: "为什么要通胀调整？",
explain_reason: "每年的物价会慢慢上涨，如果每月都提一样的金额，实际能买的东西会越来越少。",
explain_how: "怎么做？",

step_1: "第一年每月提 30,000 元",
step_2: "通胀 2%，第二年提 30,600 元",
step_3: "第三年提 31,212 元… 以此类推",
   nav_about: "品牌故事",
nav_books: "推荐书单",
   about_title: "品牌故事｜FINORA 好好存",
  about_heading: "FINORA的由来",
  about_p1: "哈喽，你是否和我一样，虽然收入稳定，但是对庞大的开销、资产盘点和未来退休财务状况感到格外焦虑？",
  about_p2: "通过资产记录、收益试算、退休预估和紧急备用金准备，我逐渐掌握了自己的财务状况。",
  about_p3: "但资产分散在不同银行和平台，甚至还有不同币种。每次盘点都要打开很多 App，Excel 表在手机上也不好用。",
  about_p4: "我相信，复利最重要的成本，是你愿意投入的时间。财务安全感，是可以一步步存出来的。所以“FINORA 好好存”，这个资产管理工具就诞生了。",
  about_p5: "欢迎你加入我们，一起“好好存、好好生活”。",
  back_to_home: "← 返回首页",
   unit_share: "股",
   current_account: "当前帐本：",
loading: "读取中...",
placeholder_monthly: "默认 30,000",
    label_policy_name: "保单名称",
    insured_amount: "保额",
    insured_years: "年期",
    annual_premium: "年缴",
    label_bank: "银行名称",
    label_note: "备注",
    label_fund_name: "基金名称",
    label_fund_units: "单位数",
    label_fund_nav: "净值",
    label_crypto_symbol: "币种",
    label_crypto_amount: "数量",
    label_crypto_price: "现价",
    total: "总金额",
free_user_limit_accounts: "当前为免费账号，仅限使用一个账本和基本功能，如需更多请升级",
upgrade_required_msg: "您当前使用的是免费账户 仅限一个账本和基本功能 如需解锁更多功能 请升级为进阶版",
  upgrade_now: "立即升级",
  close: "关闭",
login_success: "登录成功！",
    login_failed: "登录失败，请稍后再试。",
    logout_success: "已成功登出。",
    rename_prompt: "请输入新的账本名称：",
    rename_success: "账本已重命名！",
    add_success: "账本新增成功！",
    delete_success: "账本已删除！",
    confirm_delete: "确定要删除此账本？",
    account_name_required: "请输入账本名称",
exchange_rate_error: "汇率查询错误",
using_backup_rates: "使用备援汇率资料（localStorage）",
using_default_rates: "使用预设汇率资料",
exchange_rate_updated: "汇率已更新",
   label_property_name: "房产名称",
label_property_value: "估值（市价）",
label_mortgage_balance: "房贷余额",
label_interest_rate: "利率（%）",
label_years_remaining: "剩余年限",
      unit_years:"年",
   delete_title: "删除帐号与数据",
delete_intro: "您可以按照以下步骤，申请删除您的帐号及相关数据。",
delete_steps: "请通过电子邮件联系我们，标题请注明：删除帐号。我们将在收到请求后的 7 个工作日内处理并回复确认。",
delete_note: "如需更多帮助，请联系 service@finora.life",
   footer_delete_account: "删除账户",
   footer_terms: "服务条款",
    terms_title: "服务条款",
    terms_intro: "欢迎使用 FINORA 好好存。本服务条款说明您与本平台之间的权利与义务。",
    terms_use: "1. 用户责任：请确认您提供的资料正确且不涉及非法行为。",
    terms_privacy: "2. 隐私保护：我们依据隐私权条款保护您提供的资料。",
    terms_liability: "3. 平台责任：本平台不对资料准确性或使用结果负完全责任。",
    terms_change: "4. 条款变更：我们保留随时修改条款的权利，请定期查阅。",
    terms_contact: "若您对服务条款有任何疑问，欢迎通过联系我们页面与我们联系。",
   no_asset_warning_console: "找不到资产分类数据，请先到资产页建立资产",
    no_asset_warning_html: "尚未建立资产，请先至资产页新增资产",
    missing_container_error: "缺少 #asset-summary 容器"
},

"en": {
  title: "FINORA Wealth Planner",
  subtitle: "Make your assets powerful. Retire without worries.",
  asset: "Asset Manager",
  compound: "Compound Calculator",
  withdraw: "Withdrawal Planner",
  emergency: "Emergency Fund",
  accountLabel: "Select Account:",
  rename: "✏️ Rename",
  add: "➕ Add Account",
  delete: "🗑️ Delete Account",
  save: "Save",
  login: "🔐 Sign in with Google",
  logout: "🚪 Sign Out",
  langLabel: "🌐 Language:",
  privacy: "FINORA values your privacy. Your data is yours only.",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA Wealth｜Family-friendly asset organizer",
  guide: "User Guide",
  contact: "Contact Us",
  policy: "Privacy Policy",
  placeholderNewAccount: "Enter new account name",
  asset_title: "Register Your Wealth Assets",
  guide_select_type: "📢 Select asset type below (e.g., Stocks, Insurance, Crypto)",
  guide_stock_auto: "💾 US and TW stocks will fetch real-time price automatically",
  guide_currency_auto: "🔗 Exchange rate will be auto-filled for foreign currencies",
  save_btn: "💾 Save Asset",
  asset_list: "Asset List",
  asset_total: "Total Assets",
  back_to_home: "← Back to Home",
  privacy_note: "🔐 All data is saved to your Google account and cloud ledger securely.",
  user: "User:",
  account: "Account:",
  label_type: "Type:",
  label_name: "Name:",
  label_amount: "Amount",
  label_currency: "Currency:",
  label_bank: "Bank:",
  label_note: "Note:",
  label_display_currency: "💱 Display currency for total assets:",
  option_please_select: "Please select",
  option_stock: "Stock",
  option_deposit: "Deposit",
  option_cash: "Cash",
  option_property: "Property",
  option_insurance: "Insurance",
  option_fund: "Fund",
  option_crypto: "Cryptocurrency",
  option_other: "Other",
  option_股票: "Stock",
  option_定存: "Deposit",
  option_現金: "Cash",
  option_房產: "Property",
  option_儲蓄保險: "Insurance",
  option_基金: "Fund",
  option_加密貨幣: "Cryptocurrency",
  option_其他: "Other",
  footer_help: "User Guide",
  footer_contact: "Contact Us",
  footer_privacy: "Privacy Policy",
  not_logged_in: "(Not logged in)",
  no_account_selected: "(No account selected)",
  please_login_first: "⚠️ Not logged in. Please sign in with your Google account first.",
  init_error: "System initialization error. Please refresh the page.",
  total_asset: "Total Assets",
  exchange_rate_updated: "Exchange Rate Updated",
  cost: "Cost",
  label_price: "Current Price",
  market_value: "Market Value",
  profit: "Profit",
  option_select: "Please select",
  save_asset: "Save Asset",
howto_title: "User Guide",
howto_intro: "An asset integration tool for individuals, families, and freelancers to stay financially clear—and guide kids to money awareness.",
howto_feature1_title: "📒 Flexible Ledger Management",
howto_feature1_text: "Create separate accounts for different goals, suitable for all ages. Manage separately to see clearly and plan orderly.",
howto_feature2_title: "📈 Compound Growth Simulator",
howto_feature2_text: "Enter starting amount, return rate, and regular investments to simulate future asset growth powered by time.",
howto_feature3_title: "💰 Asset Integration & Currency Conversion",
howto_feature3_text: "Combine ETFs, funds, stocks, insurance, crypto, cash, and property. Automatically calculate market value and profit in TWD.",
howto_feature4_title: "⏳ Retirement Withdrawal & Risk Planner",
howto_feature4_text: "Based on your current assets and withdrawal setup, simulate retirement cash flow and see how long your money may last.",
howto_feature5_title: "🧯 Emergency Fund Estimator",
howto_feature5_text: "Enter living expenses (e.g., rent, food, childcare) to estimate how much to save for 3–6 months of emergency support.",
howto_feature6_title: "🔐 Cloud Sync + Secure Google Login",
howto_feature6_text: "One-click login and cloud storage with multi-ledger, multi-device sync. Your data belongs to you—free of ads or pressure.",
howto_cta: "Start Using Now",
howto_conclusion: "FINORA isn't just for tracking—it's your calm, secure, and free future in the making.",
privacy_title: "Privacy Policy",
privacy_intro: "FINORA respects and protects your personal data. Here's how we collect, use, and secure your information.",
privacy_section1: "1. Data Collection",
privacy_content1: "We only collect your name and email when voluntarily provided. Google Sign-In is solely used for syncing personal data.",
privacy_section2: "2. Purpose of Use",
privacy_content2: "The collected data is used for syncing accounts, usage analysis, and product improvement. It will not be sold or shared with third parties.",
privacy_section3: "3. Data Storage & Security",
privacy_content3: "All data is stored on Google Firebase Cloud with standard encryption and authentication protocols.",
privacy_section4: "4. Your Rights",
privacy_content4: "You may delete your data and accounts at any time. Please contact us if you wish to remove your entire account.",
privacy_section5: "5. Policy Updates",
privacy_content5: "We may update this policy as needed. Major updates will be announced separately and published here.",
privacy_start: "Start Using Now",
    compound_title: "Simulate a Wealthy Future",
    compound_intro: "🔢 Enter initial amount, annual return, and duration to simulate compound growth",
    compound_input_title: "📈 Compound Interest Calculator",
    label_principal: "Initial Investment (NTD):",
    label_rate: "Annual Return Rate (%):",
    label_years: "Investment Duration (years):",
    label_annual: "Annual Contribution:",
    label_monthly_money: "Monthly Contribution:",
    calculate_button: "Calculate",
    exchange_tool: "💱 Currency Converter",
    label_amount: "Amount",
    label_from: "From:",
    label_to: "To:",
    convert_button: "Convert",
    currency_label: "Asset Value Currency:",
    total_asset_loading: "💰 Loading total assets...",
    total_asset_value: "💰 Estimated Total Assets :",
    last_calculated: "📌 Last result:",
    fetching_exchange: "Fetching exchange rates...",
    invalid_exchange: "Failed to retrieve exchange rates",
    exchange_updated: "Exchange rates updated",
    using_stored_exchange: "Using saved exchange rates",
    using_default_exchange: "Using default exchange rates",
    exchange_not_ready: "⚠️ Exchange rates not ready",
    no_assets: "No asset records yet",
    asset_category_summary: "📊 Asset Category Summary",
    currency_totals: "💰 Currency Totals",
    user: "User",
    account_book: "Account Book",
    please_login: "Please log in before using this feature",
    no_account_warning: "No account book found. Please create one on the homepage.",
    please_create_account_book: "Please create an account book to use this feature",
    back_home_link: "← Back to Home",
    unit_currency: "NTD",
    compound_result_prefix: "After {years} years, estimated total assets: ",
  label_principal: "Initial Investment (NTD):",
label_rate: "Annual Return Rate (%):",
label_years: "Investment Years:",
label_annual: "Annual Regular Investment:",
label_monthly: "Monthly Regular Investment:",
compound_input_title: "📈 Compound Calculator",
calculate_button: "Calculate Compound",
last_calculated: "Last calculated:",
  exchange_tool: "Exchange Rate Converter",
label_amount: "Amount:",
label_from: "From:",
label_to: "To:",
convert_button: "Convert",
exchange_updated: "✅ Exchange rates updated",
  type_股票: "Stocks",
type_基金: "Funds",
type_加密貨幣: "Crypto",
type_儲蓄保險: "Insurance",
type_現金: "Cash",
type_房產: "Real Estate",
type_定存: "Fixed Deposit",
type_其他: "Other", 
title: "FINORA",
    emergency_title: "Emergency Fund Estimator",
    emergency_intro: "📝 Enter your fixed monthly income and expenses to build your financial moat",
    account_label: "Current Account:",
    add_income: "Add Income Item",
    add_expense: "Add Expense Item",
    income_item: "Income Item",
    expense_item: "Expense Item",
    amount: "Amount",
    monthly_income: "Monthly Income",
    monthly_expense: "Monthly Expenses",
    reserve_calc: "Reserve Suggestion",
    select_months_label: "Select Coverage Months:",
    months_option_3: "3 months",
    months_option_6: "6 months",
    months_option_9: "9 months",
    months_option_12: "12 months",
    monthly_income_total: "Total Monthly Income",
    monthly_expense_total: "Total Monthly Expenses",
    suggested_reserve: "Suggested Reserve",
    currency_unit: "NTD",
    no_account_selected_alert: "No account selected. Please log in and select an account!",
    back_home_link: "← Back to Home",
    footer_guide: "User Guide",
    footer_contact: "Contact Us",
    footer_privacy: "Privacy Policy",
    footer_copyright: "© 2025 FINORA｜Family-friendly asset management tool",
  withdraw_title: "Retirement Withdrawal Calculator | FINORA",
    withdraw_heading: "How to Spend Your Retirement Fund",
    withdraw_intro: "💶 Enter your estimated assets, withdrawal amount or rate, and optionally include return and inflation rates.",
    label_total: "Estimated Total Assets (NT$):",
    label_monthly: "Monthly Withdrawal (NT$):",
    label_withdraw_rate: "Withdrawal Rate (%):",
    label_return_rate: "Annual Return Rate (%):",
    label_inflation_rate: "Annual Inflation Rate (%):",
    placeholder_monthly: "Default: 30,000",
    btn_toggle_inflation: "💡 Adjust monthly withdrawal by inflation",
    btn_calculate: "Calculate",
    basic_withdraw: "Basic Monthly Withdrawal Estimate",
    can_last: "can last about",
    years: "years",
    months: "months",
    withdraw_rate_method: "Withdrawal Method",
    yearly: "Annually about",
    monthly: "Monthly about",
    estimated_duration: "Estimated duration",
    real_rate_calc: "Return vs. Inflation Adjustment",
    real_rate: "Real annual return rate is about",
    inflation_adjusted_withdraw_simulation: "Inflation-Adjusted Withdrawal Simulation",
    default_monthly_warn: "⚠️ Monthly withdrawal not entered, using default NT$30,000",
    year: "Year",
    yearly_out: "Annual Outflow",
    remaining_asset: "Remaining Assets",
    withdraw_until_year: "Expected to sustain until year",
    inflation_enabled: "Inflation adjustment enabled",
    inflation_disabled: "Adjust monthly withdrawal by inflation",
    please_login_first: "Please log in to use this feature.",
    recent_compound_result: "Latest compound result",
section_explanation_title: "📌 Withdrawal Methods：",

method_basic: "Basic Monthly: Total assets ÷ monthly needs = years of support.",
method_4percent: "4% Rule: Withdraw 4% or less annually, ideally lasts 30+ years.",
method_real_rate: "Return - Inflation: Calculates real purchasing power after adjusting.",
method_adjust_inflation: "Inflation Adjusted: Simulates maintaining purchasing power over time.",

btn_explain_more: "📖 What is inflation-adjusted withdrawal?",

explain_why: "Why adjust for inflation?",
explain_reason: "Prices rise over time. If you withdraw the same amount each year, it buys less and less.",
explain_how: "How does it work?",

step_1: "Year 1: Withdraw NT$30,000/month",
step_2: "2% inflation → Year 2: NT$30,600",
step_3: "Year 3: NT$31,212… and so on",
  nav_about: "About FINORA",
nav_books: "Recommended Reads",
  about_title: "Brand Story｜FINORA",
  about_heading: "The Story of FINORA",
  about_p1: "Hello! Are you like me — with a stable income but often anxious about rising expenses, scattered assets, and an uncertain retirement plan?",
  about_p2: "By tracking assets, simulating returns, planning for retirement, and building an emergency fund, I gradually gained control of my finances.",
  about_p3: "But my assets were spread across banks and platforms, in different currencies. I had to open multiple apps, and Excel sheets were hard to use on mobile.",
  about_p4: "That’s why I created FINORA — a simple asset management tool designed for people like us. I believe the most important cost of compounding is your time. Financial security can be built step by step.",
  about_p5: "Join us, and let’s start saving smart and living well together.",
  back_to_home: "← Back to Home",
  unit_share: "shares",
  current_account: "Current Account:",
loading: "Loading...",
placeholder_monthly: "Default: 30,000",
  label_policy_name: "Policy Name",
    insured_amount: "Coverage Amount",
    insured_years: "Term",
    annual_premium: "Annual Premium",
    label_bank: "Bank Name",
    label_note: "Note",
    label_fund_name: "Fund Name",
    label_fund_units: "Units",
    label_fund_nav: "NAV",
    label_crypto_symbol: "Symbol",
    label_crypto_amount: "Amount",
    label_crypto_price: "Price",
    total: "Total Value",
free_user_limit_accounts: "You are currently using the free plan with one account and basic features. Upgrade for more.",
upgrade_required_msg: "You are currently using the free version with one account and basic features Upgrade to unlock more",
  upgrade_now: "Upgrade Now",
  close: "Close",
login_success: "Login successful!",
    login_failed: "Login failed. Please try again later.",
    logout_success: "Successfully logged out.",
    rename_prompt: "Enter new account name:",
    rename_success: "Account renamed!",
    add_success: "Account created!",
    delete_success: "Account deleted!",
    confirm_delete: "Are you sure you want to delete this account?",
    account_name_required: "Please enter an account name",
  exchange_rate_error: "Exchange rate fetch error",
using_backup_rates: "Using backup exchange rates (localStorage)",
using_default_rates: "Using default exchange rates",
exchange_rate_updated: "Exchange rates updated", 
  label_property_name: "Property Name",
label_property_value: "Appraised Value (Market Price)",
label_mortgage_balance: "Mortgage Balance",
label_interest_rate: "Interest Rate (%)",
label_years_remaining: "Years Remaining",
     unit_years:"years",
  delete_title: "Delete Account and Data",
delete_intro: "You can request to delete your account and related data by following the steps below.",
delete_steps: "Please contact us via email with the subject: Delete Account. We will process and confirm your request within 7 business days.",
delete_note: "For further assistance, contact service@finora.life",
  footer_delete_account: "Delete Account",
  footer_terms: "Terms of Service",
    terms_title: "Terms of Service",
    terms_intro: "Welcome to FINORA. These Terms of Service explain your rights and obligations when using this platform.",
    terms_use: "1. User Responsibility: Please ensure the information you provide is accurate and lawful.",
    terms_privacy: "2. Privacy: Your data is protected in accordance with our privacy policy.",
    terms_liability: "3. Platform Liability: We are not fully responsible for the accuracy of data or usage outcomes.",
    terms_change: "4. Changes to Terms: We may revise these terms at any time. Please review them regularly.",
    terms_contact: "If you have any questions, feel free to contact us via the Contact page.", 
  no_asset_warning_console: "No asset data found. Please go to the Assets page to add assets first.",
    no_asset_warning_html: "⚠️ No assets found. Please add assets from the Assets page first.",
    missing_container_error: "Missing #asset-summary container"
},

  
 "ja": {
  title: "FINORA 資産管理",
  subtitle: "資産を強く、安心なリタイアへ。",
  asset: "資産2管理",
  compound: "複利計算",
  withdraw: "引き出し計画",
  emergency: "緊急資金",
  accountLabel: "帳簿の選択：",
  rename: "✏️ 名前を変更",
  add: "➕ 帳簿を追加",
  delete: "🗑️ 削除",
  save: "保存",
  login: "🔐 Googleでログイン",
  logout: "🚪 ログアウト",
  langLabel: "🌐 言語：",
  privacy: "FINORAはあなたのプライバシーを尊重します。資産はあなただけのものです。",
  version: "v0.9 beta - 2025-06-04",
  footer: "© 2025 FINORA 資産管理｜家族向けの資産統合ツール",
  guide: "使用方法",
  contact: "お問い合わせ",
  policy: "プライバシーポリシー",
  placeholderNewAccount: "新しい帳簿名を入力",
  asset_title: "資産を登録する",
  guide_select_type: "📢 下のメニューから資産の種類を選んでください（株、保険、暗号通貨など）",
  guide_stock_auto: "💾 米国株の現在価格は自動取得されます",
  guide_currency_auto: "🔗 外貨資産は最新の為替レートが自動入力されます",
  save_btn: "💾 資産を保存する",
  asset_list: "資産リスト",
  asset_total: "資産合計",
  back_to_home: "← ホームへ戻る",
  privacy_note: "🔐 データはすべてあなたのGoogleアカウントとクラウドに安全に保存されます。",
  user: "ユーザー：",
  account: "帳簿：",
  label_type: "種類：",
  label_name: "名称：",
  label_amount: "金額",
  label_currency: "通貨：",
  label_bank: "銀行名：",
  label_note: "備考：",
  label_display_currency: "💱 総資産の表示通貨：",
  option_please_select: "選択してください",
  option_stock: "株式",
  option_deposit: "定期預金",
  option_cash: "現金",
  option_property: "不動産",
  option_insurance: "保険",
  option_fund: "投資信託",
  option_crypto: "暗号通貨",
  option_other: "その他",
  option_股票: "株式",
  option_定存: "定期預金",
  option_現金: "現金",
  option_房產: "不動産",
  option_儲蓄保險: "保険",
  option_基金: "投資信託",
  option_加密貨幣: "暗号通貨",
  option_其他: "その他",
  footer_help: "使用方法",
  footer_contact: "お問い合わせ",
  footer_privacy: "プライバシーポリシー",
  not_logged_in: "（未ログイン）",
  no_account_selected: "（アカウント未選択）",
  please_login_first: "⚠️ 未ログインです。まず Google アカウントにログインしてください。",
  init_error: "システム初期化エラー。ページを再読み込みしてください。",
  total_asset: "資産合計",
  exchange_rate_updated: "為替レート更新時間",
  cost: "取得価格",
  label_price: "現在価格",
  market_value: "評価額",
  profit: "利益",
   option_select: "選択してください",
save_asset: "資産を保存する",
   howto_title: "使い方ガイド",
howto_intro: "個人、家族、フリーランスのために設計された資産統合ツール。財務状況を把握し、子どもと一緒にお金の感覚を育む。",
howto_feature1_title: "📒 帳簿を分けて自由に管理",
howto_feature1_text: "目的ごとに帳簿を分けて管理。年齢を問わず使いやすく、人生の目標が見えやすくなります。",
howto_feature2_title: "📈 複利成長シミュレーション",
howto_feature2_text: "初期金額・利回り・定期投入を入力し、時間とともに資産がどのように増えるかを可視化。",
howto_feature3_title: "💰 資産統合と通貨換算",
howto_feature3_text: "ETF、ファンド、株、保険、暗号通貨、現金、不動産を統合して、時価と利益を自動計算。TWD換算にも対応。",
howto_feature4_title: "⏳ 退職後の引き出しとリスク試算",
howto_feature4_text: "現在の資産と引き出し設定に基づき、老後のキャッシュフローをシミュレート。将来の安心を可視化します。",
howto_feature5_title: "🧯 緊急資金の試算ツール",
howto_feature5_text: "生活費（家賃・食費・育児など）を入力し、3〜6か月分の必要な緊急資金額を自動試算。安心のクッションを作成。",
howto_feature6_title: "🔐 クラウド同期 + Google安全ログイン",
howto_feature6_text: "ワンクリックでログイン＆クラウド保存。複数の帳簿・デバイスで同期可能。広告なし、安心の個人管理。",
howto_cta: "今すぐ使い始める",
howto_conclusion: "「好好存」はただの記帳ではなく、未来の自由と安心をあなたに届ける財務基盤です。",
privacy_title: "プライバシーポリシー",
privacy_intro: "FINORA｜好好存は、ユーザーの個人情報を尊重し、保護します。以下に、情報の収集、利用、保護について説明します。",
privacy_section1: "1. 情報の収集",
privacy_content1: "ユーザーが自発的に提供する場合に限り、氏名やメールアドレスなどの情報を収集します。Google ログインはデータ同期のみに使用されます。",
privacy_section2: "2. 利用目的",
privacy_content2: "収集した情報は帳簿同期、機能分析、製品改善のみに使用され、第三者に提供・販売されることはありません。",
privacy_section3: "3. データの保存とセキュリティ",
privacy_content3: "すべてのデータは Google Firebase Cloud に保存され、暗号化と認証により保護されています。",
privacy_section4: "4. ユーザーの権利",
privacy_content4: "ユーザーは帳簿や個人情報をいつでも削除できます。アカウント削除を希望する場合はご連絡ください。",
privacy_section5: "5. ポリシーの更新",
privacy_content5: "必要に応じてポリシーを更新します。重大な変更は別途通知し、本ページに掲載します。",
privacy_start: "今すぐ始める",
    compound_title: "未来資産のシミュレーション",
    compound_intro: "🔢 初期金額・年利・期間を入力して、複利成長をシミュレート",
    compound_input_title: "📈 複利計算機",
    label_principal: "初期投資額（元）：",
    label_rate: "年利率（%）：",
    label_years: "投資年数：",
    label_annual: "年間積立額：",
    label_monthly: "毎月積立額：",
    calculate_button: "計算する",
    exchange_tool: "💱 為替レート換算",
    label_amount: "金額",
    label_from: "変換元：",
    label_to: "変換先：",
    convert_button: "換算",
    currency_label: "資産評価通貨：",
    total_asset_loading: "💰 資産合計を読み込み中...",
    total_asset_value: "💰 総資産見積額：",
    last_calculated: "📌 最後の試算結果：",
    fetching_exchange: "為替レート取得中...",
    invalid_exchange: "為替レートの取得に失敗しました",
    exchange_updated: "為替レート更新済み",
    using_stored_exchange: "保存済みのレートを使用中",
    using_default_exchange: "デフォルトのレートを使用中",
    exchange_not_ready: "⚠️ 為替レートが準備できていません",
    no_assets: "資産記録がまだありません",
    asset_category_summary: "📊 資産カテゴリーの合計",
    currency_totals: "💰 通貨別合計",
    user: "ユーザー",
    account_book: "帳簿",
    please_login: "この機能を使用するにはログインしてください",
    no_account_warning: "帳簿が存在しません。ホームで新規作成してください。",
    please_create_account_book: "帳簿を作成してからこの機能を利用してください",
    back_home_link: "← ホームへ戻る",
    unit_currency: "元",
    compound_result_prefix: " {years}年後の推定総資産：",
   label_principal: "初期投資金額（元）：",
label_rate: "年利回り（%）：",
label_years: "投資年数：",
label_annual: "年間定期投資額：",
label_monthly_money: "毎月定期投資額：",
compound_input_title: "📈 複利計算",
calculate_button: "複利を計算",
last_calculated: "前回の計算結果：",
   exchange_tool: "為替換算",
label_amount: "金額：",
label_from: "から：",
label_to: "へ：",
convert_button: "換算",
exchange_updated: "✅ 為替レート更新完了",
   type_股票: "株式",
type_基金: "ファンド",
type_加密貨幣: "暗号資産",
type_儲蓄保險: "保険",
type_現金: "現金",
type_房產: "不動産",
type_定存: "定期預金",
type_其他: "その他", 
   title: "FINORA",
    emergency_title: "緊急予備資金試算",
    emergency_intro: "📝 毎月の収入と支出を入力して、財務の堀を築こう",
    account_label: "現在の帳簿：",
    add_income: "収入項目を追加",
    add_expense: "支出項目を追加",
    income_item: "収入項目",
    expense_item: "支出項目",
    amount: "金額",
    monthly_income: "毎月の収入記録",
    monthly_expense: "毎月の支出記録",
    reserve_calc: "予備資金の試算",
    select_months_label: "カバー月数を選択：",
    months_option_3: "3 ヶ月",
    months_option_6: "6 ヶ月",
    months_option_9: "9 ヶ月",
    months_option_12: "12 ヶ月",
    monthly_income_total: "毎月の収入合計",
    monthly_expense_total: "毎月の支出合計",
    suggested_reserve: "推奨予備資金",
    currency_unit: "円",
    no_account_selected_alert: "帳簿が選択されていません。まずログインして選択してください！",
    back_home_link: "← ホームへ戻る",
    footer_guide: "使用方法",
    footer_contact: "お問い合わせ",
    footer_privacy: "プライバシーポリシー",
    footer_copyright: "© 2025 FINORA｜家族向け資産統合ツール",
   withdraw_title: "退職引き出し試算｜FINORA",
    withdraw_heading: "退職金の使い方",
    withdraw_intro: "💶 推定資産、引き出し額または比率を入力し、年利回りとインフレ率も追加可能です。",
    label_total: "推定資産総額（NT$）：",
    label_monthly: "月額引き出し（NT$）：",
    label_withdraw_rate: "引き出し率（％）：",
    label_return_rate: "年間利回り（％）：",
    label_inflation_rate: "年間インフレ率（％）：",
    placeholder_monthly: "初期値 30,000",
    btn_toggle_inflation: "💡 インフレに応じて引き出し額を調整",
    btn_calculate: "試算",
    basic_withdraw: "基本的な月額引き出し試算",
    can_last: "維持可能期間：約",
    years: "年",
    months: "ヶ月",
    withdraw_rate_method: "引き出し方式",
    yearly: "年間 約",
    monthly: "月額 約",
    estimated_duration: "想定持続期間",
    real_rate_calc: "利回りとインフレ調整",
    real_rate: "実質年利回り：約",
    inflation_adjusted_withdraw_simulation: "インフレ調整付き引き出しシミュレーション",
    default_monthly_warn: "⚠️ 月額引き出し未入力のため、初期値 NT$30,000 で試算します",
    year: "",
    yearly_out: "年間支出",
    remaining_asset: "残り資産",
    withdraw_until_year: "持続可能年数：第",
    inflation_enabled: "インフレ調整が有効です",
    inflation_disabled: "インフレに応じて引き出し額を調整",
    please_login_first: "この機能を使用するにはログインが必要です。",
    recent_compound_result: "最近の複利結果",
section_explanation_title: "📌 引き出し方法の説明：",

method_basic: "基本月額：総資産 ÷ 月額支出 = 支持可能な年数",
method_4percent: "4%ルール：年間4%未満を引き出せば30年以上持続可能",
method_real_rate: "利回り－インフレ：インフレ調整後の実質購買力を試算",
method_adjust_inflation: "インフレ調整引き出し：購買力を維持するため、毎年金額を上昇させる",

btn_explain_more: "📖 インフレ調整引き出しとは？",

explain_why: "なぜインフレ調整が必要？",
explain_reason: "毎年物価が上がるため、同じ金額では買える物が少なくなる。",
explain_how: "どうやって？",

step_1: "1年目：月額 30,000元 を引き出す",
step_2: "インフレ 2%、2年目は 30,600元",
step_3: "3年目は 31,212元… 以降同様",
nav_about: "ブランドストーリー",
nav_books: "おすすめ書籍",
   about_title: "ブランドストーリー｜FINORA",
  about_heading: "FINORAが生まれた理由",
  about_p1: "こんにちは。安定した収入があっても、支出の多さや資産の管理、将来の退職資金に不安を感じたことはありませんか？",
  about_p2: "資産の記録、利回りの試算、退職の見通し、緊急予備資金の準備を通して、少しずつ自分の財務状況を把握できるようになりました。",
  about_p3: "しかし資産は複数の銀行やプラットフォームに分散され、通貨もバラバラ。毎回いくつものアプリを開く必要があり、Excelはスマホでは使いにくいと感じました。",
  about_p4: "だからこそ、『FINORA 好好存』という私たちのための資産管理ツールを開発しました。複利で一番大切なのは、時間をかけること。財務の安心感は、一歩一歩積み上げるものです。",
  about_p5: "ぜひ、私たちと一緒に「しっかり貯めて、しっかり暮らす」人生を始めましょう。",
  back_to_home: "← ホームへ戻る",
   unit_share: "株",
   current_account: "現在の帳本：",
loading: "読み込み中...",
placeholder_monthly: "デフォルト：30,000",
   label_policy_name: "保険名",
    insured_amount: "保障額",
    insured_years: "年数",
    annual_premium: "年間保険料",
    label_bank: "銀行名",
    label_note: "備考",
    label_fund_name: "ファンド名",
    label_fund_units: "口数",
    label_fund_nav: "基準価額",
    label_crypto_symbol: "銘柄",
    label_crypto_amount: "数量",
    label_crypto_price: "価格",
    total: "合計金額",
free_user_limit_accounts: "現在は無料プランを利用中です。アカウントは1つまでで、基本機能のみ使用できます。アップグレードをご検討ください。",
upgrade_required_msg: "現在は無料プランを利用中です アカウントは1つまで 基本機能のみ使用可能です アップグレードで全機能を解放できます",
  upgrade_now: "今すぐアップグレード",
  close: "閉じる",
   login_success: "ログイン成功！",
    login_failed: "ログインに失敗しました。後で再試行してください。",
    logout_success: "ログアウトしました。",
    rename_prompt: "新しい帳簿名を入力してください：",
    rename_success: "帳簿名を変更しました！",
    add_success: "新しい帳簿を作成しました！",
    delete_success: "帳簿を削除しました！",
    confirm_delete: "この帳簿を削除してもよろしいですか？",
    account_name_required: "帳簿名を入力してください",
   exchange_rate_error: "為替レート取得エラー",
using_backup_rates: "バックアップの為替レートを使用中（localStorage）",
using_default_rates: "デフォルトの為替レートを使用中",
exchange_rate_updated: "為替レートを更新しました",
   label_property_name: "不動産名",
label_property_value: "評価額（時価）",
label_mortgage_balance: "住宅ローン残高",
label_interest_rate: "金利（%）",
label_years_remaining: "残存年数",
      unit_years:"年",
   delete_title: "アカウントとデータの削除",
delete_intro: "以下の手順に従って、アカウントと関連データの削除をリクエストできます。",
delete_steps: "「アカウント削除」という件名でメールにてご連絡ください。7営業日以内に処理し、確認を返信いたします。",
delete_note: "詳細は service@finora.life までご連絡ください。",
   footer_delete_account: "アカウント削除",
   footer_terms: "利用規約",
    terms_title: "利用規約",
    terms_intro: "FINORAをご利用いただきありがとうございます。本規約は本サービスの利用に関する権利と義務を説明します。",
    terms_use: "1. ユーザーの責任：提供された情報が正確であり、違法行為を含まないことを確認してください。",
    terms_privacy: "2. プライバシー保護：私たちはプライバシーポリシーに基づき、提供された情報を保護します。",
    terms_liability: "3. プラットフォームの責任：本サービスの内容や結果について、完全な責任を負うものではありません。",
    terms_change: "4. 規約の変更：規約は随時変更される可能性があります。定期的にご確認ください。",
    terms_contact: "ご不明な点がある場合は、お問い合わせページよりご連絡ください。",
   no_asset_warning_console: "資産データが見つかりません。先に資産ページで追加してください。",
    no_asset_warning_html: "⚠️ 資産が未登録です。資産ページで追加してください。",
    missing_container_error: "#asset-summary コンテナが見つかりません"

  }
};

